version: '3'

services:
  db:
    image: postgres:15.6-alpine3.19
    restart: unless-stopped
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: rinha-de-backend
      PGDATA: /data
    volumes:
      - "db_data:/data"
      - "./confg-files/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql"
    networks:
      - rinha-net
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: "0.5"

  lb:
    image: nginx:1.25.4-alpine-slim
    networks:
      - rinha-net
    depends_on:
      - app1
      - app2
    ports:
      - 9999:9999
    volumes:
      - "./confg-files/nginx.conf:/etc/nginx/nginx.conf"
    deploy:
      resources:
        limits:
          memory: 500M
          cpus: "0.25"

  app1: &app1
    depends_on:
      - db
    build: ./
    networks:
      - rinha-net
    environment:
      DB_URI: postgresql+psycopg2://app:app@db:5432/rinha-de-backend
      FASTAPI_PRODUCTION: true
    deploy:
      resources:
        limits:
          memory: 750M
          cpus: "0.375"

  app2:
    <<: *app1

volumes:
  db_data:


networks:
  rinha-net:
