"""added index to id and search

Revision ID: d2477e526aea
Revises: c9651273e714
Create Date: 2024-04-15 21:49:04.062845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2477e526aea'
down_revision: Union[str, None] = 'c9651273e714'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_person_id'), 'person', ['id'], unique=True)
    op.create_index(op.f('ix_person_search'), 'person', ['search'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_person_search'), table_name='person')
    op.drop_index(op.f('ix_person_id'), table_name='person')
    # ### end Alembic commands ###
