"""add stack to person

Revision ID: daad122889c4
Revises: 4f6c73da49f7
Create Date: 2024-04-15 17:23:39.615671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'daad122889c4'
down_revision: Union[str, None] = '4f6c73da49f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('stack', sa.ARRAY(sa.String(length=32)), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'stack')
    # ### end Alembic commands ###
